path: "../web/photos"
extensions: [ gif, jpg, JPG, jpeg, png ]

image_optimizer:
    jpegoptim:
        bin: /usr/bin/jpegoptim
        max: 70
    size:
        thumbnail: { width: 190, height: 190 }
        image: { width: 1024, height: 768 }
